### ISSUE TITLE
attempt to index upvalue 'Constants' (a nil value)

### ISSUE THREAD

**Issue by Katie-Fish** [hutcho/TodoChecklister#1]
hi. i LOVE this, so thanks for making it!! but i'm encountering 2 errors:
~~~
1x TodoChecklister/src/modules/debug.lua:20: attempt to index upvalue 'Constants' (a nil value)
[string "@TodoChecklister/src/modules/debug.lua"]:20: in function `Init'
[string "@TodoChecklister/src/init.lua"]:44: in function <TodoChecklister/src/init.lua:38>

Locals:
self = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index upvalue 'Constants' (a nil value)"
Constants = nil

~~~

2x TodoChecklister/src/config/config.xml:2 Error loading TodoChecklister/constants.lua

**Comment by hutcho** [comment]
Thanks @Katie-Fish, can you please provide your wow version, and what are you doing in-game when you get these errors?

**Comment by hutcho** [comment]
I found a bug, the constants.lua file was missing. It's been added now. [b3685c5](https://github.com/hutcho/TodoChecklister/commit/b3685c59006a0cad1a2c1e1cc44556fe66f894e0)

**Comment by hutcho** [comment]
Fixed in tag 1.0.1. Please update the addon to version 1.0.1 and let me know if the error still occurs. Thank you for raising the issue, it's much appreciated.

**Comment by Katie-Fish** [comment]
You're awesome!! Thanks so much for the repair. Have a beautiful day 🌺🌻🌹
________________________________

**Comment by Katie-Fish** [comment]
Hey - can you tell me where i'd be able to change the text color of the floating list? I've gone through all the files, but just can't figure it out. Just a file name and constant name would be great, if you wouldn't mind.  🙂

________________________________

**Comment by hutcho** [comment]
I opened #2 to discuss the colour feature. Thank you for the idea.

**Comment by Katie-Fish** [comment]
Hey - no problem! I love colors!  in the meantime, as it sounds like you might use the option - can you please tell me which file the text color for the floating ui is in? I'll just make a quick change for myself and then i can play without the yellow in my eyes.  🙂

And. Since you're open to ideas - you might add just a nice, clean font or 2. I went in and added an Arial, Myriad and PT_Sans.  🙂

Thanks so much for this!

________________________________

**Comment by hutcho** [comment]
In TodoChecklister.xml line 55 the value "GameFontNormalSmall" is probably what makes the text yellow. The colour is inherited from game fonts and not set by the addon. Theres a new addon version out now that has a colour picker in the esc Options menu.

The font suggestion is an interesting idea. Could you please open a new issue and include snippets of your code? Or send a pull request if you like.

**Comment by Katie-Fish** [comment]
Ok. i contemplated just not emailing you back.  but, total transparency here for the sake of honesty and a giggle.

I use 2 todo addons for different things, and love them both for different reasons. Yours was great, but the other needed a couple of improvements. I've been messaging you about the other addon. And i just realized that when i read your email with the file name, "todochecklister". Oh damn. That's not the one that i had problems with.

So LOL. I'm sorry! But i'm really glad you added the color option. There's probably no need to change the font. I'm so sorry!! My brain doesn't always work well.

Have a beautiful day, and i do appreciate your work.

❤️❤️❤️



________________________________
